/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * EC Site Member API
 * ECサイトの一般会員向けAPI
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Error {
  errors?: string[];
}

export interface Member {
  firstName: string;
  firstNameKana: string;
  lastName: string;
  lastNameKana: string;
  tel: string;
  gender: number;
  birthday: string;
  email: string;
}

export interface ShopCategory {
  /** カテゴリID
- 1: メンズファッション
- 2: レディースファッション
- 3: キッズファッション
- 4: シューズ
- 5: バッグ
- 6: アクセサリー
- 7: スポーツ
- 8: アウトドア
- 9: コスメ・美容
- 10: ヘルス・ボディケア
- 11: フード・グルメ
- 12: インテリア・雑貨
 */
  id: number;
  /** カテゴリの表示名 */
  name: string;
}

export interface Shop {
  id: number;
  shopCategories: ShopCategory[];
  /** 画像URLがない場合は空文字列を返します */
  imageUrl: string;
  name: string;
  description: string;
  createdAt: string;
}

export interface ItemCategory {
  /** カテゴリID
- 1: トップス
- 2: ボトムス
- 3: アウター
- 4: ワンピース
- 5: スーツ・フォーマル
- 6: バッグ
- 7: シューズ
- 8: アクセサリー
- 9: 帽子
- 10: 小物
 */
  id: number;
  /** カテゴリの表示名 */
  name: string;
}

export interface Item {
  id: number;
  itemCategories: ItemCategory[];
  imageUrl: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  createdAt: string;
  reviews: Review[];
}

export interface Review {
  id: number;
  title: string;
  comment: string;
  rating: number;
}

export interface ShippingInfo {
  id: number;
  postalCode: string;
  country: string;
  prefecture: string;
  city: string;
  address: string;
  building?: string;
}

export interface ReleaseInfo {
  id: number;
  title: string;
  body: string;
  createdAt: string;
}

export interface CartItem {
  id: number;
  imageUrl: string;
  name: string;
  description: string;
  price: number;
  quantity: number;
  stock: number;
  shopId: number;
}

export type PurchasePurchaseItemsItemItem = {
  id: number;
  imageUrl: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  status: number;
  shopId: number;
};

export type PurchasePurchaseItemsItem = {
  id: number;
  quantity: number;
  subtotal: number;
  item: PurchasePurchaseItemsItemItem;
};

export interface Purchase {
  id: number;
  totalPrice: number;
  createdAt: string;
  purchaseItems: PurchasePurchaseItemsItem[];
}

export interface PaginatedResponse {
  totalPages?: number;
  totalCount?: number;
  currentPage?: number;
  /** @nullable */
  nextPage?: number | null;
  hasNext?: boolean;
}

export type GetCsrf200 = {
  csrfToken: string;
};

export type GetCsrf401 = {
  message: string;
};

export type PostSignUpBodyMember = {
  firstName: string;
  firstNameKana: string;
  lastName: string;
  lastNameKana: string;
  tel: string;
  gender: number;
  birthday: string;
  email: string;
  password: string;
  passwordConfirmation: string;
};

export type PostSignUpBody = {
  member: PostSignUpBodyMember;
};

export type PostSignInBodyMember = {
  email: string;
  password: string;
};

export type PostSignInBody = {
  member: PostSignInBodyMember;
};

export type PostSignIn401 = {
  errors: string[];
};

export type DeleteSignOut200 = {
  message: string;
};

export type GetIdentity401 = {
  message?: string;
};

export type PatchProfileBodyMember = {
  firstName: string;
  firstNameKana: string;
  lastName: string;
  lastNameKana: string;
  tel: string;
  gender: number;
  birthday: string;
  email: string;
  password?: string;
  passwordConfirmation?: string;
};

export type PatchProfileBody = {
  member: PatchProfileBodyMember;
};

export type PatchProfile401 = {
  message: string;
};

export type GetShippingInfo401 = {
  message: string;
};

export type PostShippingInfoBodyShippingInfo = {
  postalCode: string;
  country: string;
  prefecture: string;
  city: string;
  address: string;
  building?: string;
};

export type PostShippingInfoBody = {
  shippingInfo: PostShippingInfoBodyShippingInfo;
};

export type PostShippingInfo401 = {
  message: string;
};

export type GetShippingInfoId401 = {
  message: string;
};

export type PatchShippingInfoIdBodyShippingInfo = {
  postalCode: string;
  country: string;
  prefecture: string;
  city: string;
  address: string;
  building?: string;
};

export type PatchShippingInfoIdBody = {
  shippingInfo: PatchShippingInfoIdBodyShippingInfo;
};

export type PatchShippingInfoId401 = {
  message: string;
};

export type DeleteShippingInfoId401 = {
  message: string;
};

export type GetShopsParams = {
page?: number;
};

export type GetShops200AllOf = {
  shops: Shop[];
};

export type GetShops200 = GetShops200AllOf & PaginatedResponse & Required<Pick<GetShops200AllOf & PaginatedResponse, 'totalPages' | 'totalCount' | 'currentPage' | 'nextPage' | 'hasNext'>>;

export type GetItemsParams = {
page?: number;
};

export type GetItems200 = {
  items: Item[];
  totalPages: number;
  totalCount: number;
  currentPage: number;
  /** @nullable */
  nextPage: number | null;
  hasNext: boolean;
};

export type GetReviewsParams = {
page?: number;
};

export type GetReviews200 = {
  reviews: Review[];
  totalPages: number;
  totalCount: number;
  currentPage: number;
  /** @nullable */
  nextPage: number | null;
  hasNext: boolean;
};

export type GetReviews401 = {
  message: string;
};

export type PostReviewsBodyReview = {
  itemId: number;
  title: string;
  comment: string;
  rating: number;
};

export type PostReviewsBody = {
  review: PostReviewsBodyReview;
};

export type PostReviews401 = {
  message: string;
};

export type DeleteReviewsId401 = {
  message: string;
};

export type GetReleaseInfoParams = {
page?: number;
};

export type GetFavoriteItemsParams = {
page?: number;
};

export type GetFavoriteItems200 = {
  favoriteItems: Item[];
  totalPages: number;
  totalCount: number;
  currentPage: number;
  /** @nullable */
  nextPage: number | null;
  hasNext: boolean;
};

export type GetFavoriteItems401 = {
  message: string;
};

export type PutFavoriteItemsId401 = {
  message: string;
};

export type GetCartItems401 = {
  message: string;
};

export type PostCartItemsBodyCart = {
  itemId: number;
  quantity: number;
};

export type PostCartItemsBody = {
  cart: PostCartItemsBodyCart;
};

export type PostCartItems401 = {
  message: string;
};

export type DeleteCartItemsId401 = {
  message: string;
};

export type GetPurchasesParams = {
page?: number;
};

export type GetPurchases200 = {
  purchases: Purchase[];
  totalPages: number;
  totalCount: number;
  currentPage: number;
  /** @nullable */
  nextPage: number | null;
  hasNext: boolean;
};

export type PostPurchases201 = {
  message: string;
};

export type PostPurchases401 = {
  message: string;
};

export type DeletePurchasesId401 = {
  message: string;
};

/**
 * @summary CSRFトークンを取得
 */
export const getCsrf = <TData = AxiosResponse<GetCsrf200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/csrf`,options
    );
  }

/**
 * @summary 会員登録
 */
export const postSignUp = <TData = AxiosResponse<void>>(
    postSignUpBody: PostSignUpBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/sign_up`,
      postSignUpBody,options
    );
  }

/**
 * @summary ログイン
 */
export const postSignIn = <TData = AxiosResponse<void>>(
    postSignInBody: PostSignInBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/sign_in`,
      postSignInBody,options
    );
  }

/**
 * @summary ログアウト
 */
export const deleteSignOut = <TData = AxiosResponse<DeleteSignOut200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/sign_out`,options
    );
  }

/**
 * @summary 会員情報取得
 */
export const getIdentity = <TData = AxiosResponse<Member>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/identity`,options
    );
  }

/**
 * @summary 会員情報更新
 */
export const patchProfile = <TData = AxiosResponse<void>>(
    patchProfileBody: PatchProfileBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/profile`,
      patchProfileBody,options
    );
  }

/**
 * @summary 配送先一覧取得
 */
export const getShippingInfo = <TData = AxiosResponse<ShippingInfo[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/shipping_info`,options
    );
  }

/**
 * @summary 配送先作成
 */
export const postShippingInfo = <TData = AxiosResponse<void>>(
    postShippingInfoBody: PostShippingInfoBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/shipping_info`,
      postShippingInfoBody,options
    );
  }

/**
 * @summary 配送先詳細取得
 */
export const getShippingInfoId = <TData = AxiosResponse<ShippingInfo>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/shipping_info/${id}`,options
    );
  }

/**
 * @summary 配送先更新
 */
export const patchShippingInfoId = <TData = AxiosResponse<void>>(
    id: number,
    patchShippingInfoIdBody: PatchShippingInfoIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/shipping_info/${id}`,
      patchShippingInfoIdBody,options
    );
  }

/**
 * @summary 配送先削除
 */
export const deleteShippingInfoId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/shipping_info/${id}`,options
    );
  }

/**
 * @summary ショップ一覧取得
 */
export const getShops = <TData = AxiosResponse<GetShops200>>(
    params?: GetShopsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/shops`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary ショップ詳細取得
 */
export const getShopsId = <TData = AxiosResponse<Shop>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/shops/${id}`,options
    );
  }

/**
 * @summary 商品一覧取得
 */
export const getItems = <TData = AxiosResponse<GetItems200>>(
    params?: GetItemsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 商品詳細取得
 */
export const getItemsId = <TData = AxiosResponse<Item>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/items/${id}`,options
    );
  }

/**
 * @summary レビュー一覧取得
 */
export const getReviews = <TData = AxiosResponse<GetReviews200>>(
    params?: GetReviewsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/reviews`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary レビュー投稿
 */
export const postReviews = <TData = AxiosResponse<void>>(
    postReviewsBody: PostReviewsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/reviews`,
      postReviewsBody,options
    );
  }

/**
 * @summary レビュー削除
 */
export const deleteReviewsId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/reviews/${id}`,options
    );
  }

/**
 * @summary お知らせ一覧取得
 */
export const getReleaseInfo = <TData = AxiosResponse<ReleaseInfo[]>>(
    params?: GetReleaseInfoParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/release_info`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary お知らせ詳細取得
 */
export const getReleaseInfoId = <TData = AxiosResponse<ReleaseInfo>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/release_info/${id}`,options
    );
  }

/**
 * @summary お気に入り商品一覧取得
 */
export const getFavoriteItems = <TData = AxiosResponse<GetFavoriteItems200>>(
    params?: GetFavoriteItemsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/favorite_items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary お気に入り商品更新
 */
export const putFavoriteItemsId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/favorite_items/${id}`,undefined,options
    );
  }

/**
 * @summary カート商品一覧取得
 */
export const getCartItems = <TData = AxiosResponse<CartItem[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/cart_items`,options
    );
  }

/**
 * @summary カート商品追加
 */
export const postCartItems = <TData = AxiosResponse<void>>(
    postCartItemsBody: PostCartItemsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/cart_items`,
      postCartItemsBody,options
    );
  }

/**
 * @summary カート商品削除
 */
export const deleteCartItemsId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/cart_items/${id}`,options
    );
  }

/**
 * @summary 購入履歴一覧取得
 */
export const getPurchases = <TData = AxiosResponse<GetPurchases200>>(
    params?: GetPurchasesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/purchases`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 商品購入
 */
export const postPurchases = <TData = AxiosResponse<PostPurchases201>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/purchases`,undefined,options
    );
  }

/**
 * @summary 購入をキャンセル
 */
export const deletePurchasesId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/purchases/${id}`,options
    );
  }

export type GetCsrfResult = AxiosResponse<GetCsrf200>
export type PostSignUpResult = AxiosResponse<void>
export type PostSignInResult = AxiosResponse<void>
export type DeleteSignOutResult = AxiosResponse<DeleteSignOut200>
export type GetIdentityResult = AxiosResponse<Member>
export type PatchProfileResult = AxiosResponse<void>
export type GetShippingInfoResult = AxiosResponse<ShippingInfo[]>
export type PostShippingInfoResult = AxiosResponse<void>
export type GetShippingInfoIdResult = AxiosResponse<ShippingInfo>
export type PatchShippingInfoIdResult = AxiosResponse<void>
export type DeleteShippingInfoIdResult = AxiosResponse<void>
export type GetShopsResult = AxiosResponse<GetShops200>
export type GetShopsIdResult = AxiosResponse<Shop>
export type GetItemsResult = AxiosResponse<GetItems200>
export type GetItemsIdResult = AxiosResponse<Item>
export type GetReviewsResult = AxiosResponse<GetReviews200>
export type PostReviewsResult = AxiosResponse<void>
export type DeleteReviewsIdResult = AxiosResponse<void>
export type GetReleaseInfoResult = AxiosResponse<ReleaseInfo[]>
export type GetReleaseInfoIdResult = AxiosResponse<ReleaseInfo>
export type GetFavoriteItemsResult = AxiosResponse<GetFavoriteItems200>
export type PutFavoriteItemsIdResult = AxiosResponse<void>
export type GetCartItemsResult = AxiosResponse<CartItem[]>
export type PostCartItemsResult = AxiosResponse<void>
export type DeleteCartItemsIdResult = AxiosResponse<void>
export type GetPurchasesResult = AxiosResponse<GetPurchases200>
export type PostPurchasesResult = AxiosResponse<PostPurchases201>
export type DeletePurchasesIdResult = AxiosResponse<void>
